server:
  port: 7052

spring:
  application:
    name: USER-SERVICE
  profiles:
      active: dev
  datasource:
    url: jdbc:mysql://localhost:3397/microservices
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  config:
    import: optional:configserver:http://localhost:7054  # [optional] To get rid from application fallback.
      

  jpa:
    hibernate:
      ddl-auto: update   # <- DB entries auto update
    show-sql: true       # <- SQL true 
 # profiles:
  #  active: prod
management:
  health:
    circuitbreakers:
      enabled: true

  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always


resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        
        
  retry:
    instance:
      ratingHotelService:
        max-attempts: 3
        wait-duration: 5s
        
        
  ratelimiter:
    instances:
      userRateLimiter:
        limitForPeriod: 2
        limitRefreshPeriod: 10s
        timeoutDuration: 0
    
